name: chesssignal

services:
  app:
    build: .
    ports:
      - "${PORT:-7861}:7861"
    env_file:
      - .env
    depends_on:
      - database
  database:
    image: mongo:latest
    volumes:
      - chesssignal-database:/data/db
    attach: false

volumes:
  chesssignal-database: